import type { IconType } from "react-icons";
import {
  FaCog,
  FaDatabase,
  FaDocker,
  FaGoogle,
  FaJava,
  FaLinux,
  FaMicrochip,
  FaPython,
  FaReact,
  FaServer,
} from "react-icons/fa";
import {
  SiAnthropic,
  SiArm,
  SiC,
  SiCplusplus,
  SiElectron,
  SiFirebase,
  SiFlask,
  SiGo,
  SiMongodb,
  SiNextdotjs,
  SiNumpy,
  SiNvidia,
  SiOpenaigym,
  SiPandas,
  SiPostgresql,
  SiPytorch,
  SiScikitlearn,
  SiSqlite,
  SiSupabase,
  SiTensorflow,
  SiThreedotjs,
  SiTypescript,
  SiVercel,
} from "react-icons/si";

export const techIcons: Record<string, IconType> = {
  React: FaReact,
  "Next.js": SiNextdotjs,
  TypeScript: SiTypescript,
  JavaScript: FaReact,
  Firebase: SiFirebase,
  MongoDB: SiMongodb,
  Go: SiGo,
  Python: FaPython,
  "C++": SiCplusplus,
  C: SiC,
  Linux: FaLinux,
  Docker: FaDocker,
  gRPC: FaServer,
  Java: FaJava,
  JSP: FaJava,
  SQL: FaDatabase,
  Playwright: FaCog,
  GCP: FaGoogle,
  BigQuery: FaGoogle,
  PyTorch: SiPytorch,
  TensorFlow: SiTensorflow,
  "Scikit-learn": SiScikitlearn,
  Pandas: SiPandas,
  NumPy: SiNumpy,
  Electron: SiElectron,
  SQLite: SiSqlite,
  OpenAI: SiOpenaigym,
  Claude: SiAnthropic,
  "Hugging Face": SiNvidia,
  ARM: SiArm,
  NVIDIA: SiNvidia,
  PostgreSQL: SiPostgresql,
  Supabase: SiSupabase,
  Vercel: SiVercel,
  Threejs: SiThreedotjs,
  Flask: SiFlask,
  CUDA: SiNvidia,
  Llama: SiNvidia,
  gdb: FaMicrochip,
  GDB: FaMicrochip,
  Valgrind: FaMicrochip,
  Gurobi: SiNumpy,
  "RIPE Atlas API": FaServer,
  Prisma: FaServer,
};

export function TechIcon({ name, className }: { name: string; className?: string }) {
  const Icon = techIcons[name];
  if (!Icon) return null;
  return <Icon className={className} aria-hidden />;
}